# The Binomial Test

## Overview

The **binomial test** is used to make inferences about a proportion or response 
rate based on a series of independent observations, each resulting in one of two
possible mutually exclusive outcomes, such as: 

    + response to treatment vs. no response

    + cure or no cure

    + survival or death

    + event vs non-event (in general)

The total number of *events* in n observations, X, follows the binomial probability
distribution. Intuitively, the sample proportion, X/n, would be a good estimate of
the unknown population proportion, p. Statistically, it is the best estimate.


You want to determine whether the population proportion, p, differs from a 
hypothesized value, p~0~. If the unknown proportion, p, equals p~0, then the estimated
proportion, X/n, should be close to p~0~, i.e., X should be close to n * p~0~.
When p differs from p~0~, X might be much larger or smaller than n * p~0~.

SAS function, **probbnml()** can be used to determine X~L~ and X~U~ (lower limit and 
upper limit)



subscript example: H~2~SO~4~
superscript example: H^2^


## proc freq to calculate Wald CI
